language: android
jdk: oraclejdk8

branches:
  only:
    - master

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

script:
  - ./gradlew :library:build